baseURL = "https://reu4752.github.io/"
languageCode = "ko-KR"
title = "ReU's Blog"

theme = "hugo-hello-programmer-theme"

paginate = 2

disqusShortname = "XXXX"
googleAnalytics = "UA-XXXXXXXX-X"

[author]
    name = "ReU"
    email = "liyu4752@gmail.com"
